#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pcmanfm
Version  : 1.3.2
Release  : 5
URL      : https://sourceforge.net/projects/pcmanfm/files/PCManFM%20%2B%20Libfm%20%28tarball%20release%29/PCManFM/pcmanfm-1.3.2.tar.xz
Source0  : https://sourceforge.net/projects/pcmanfm/files/PCManFM%20%2B%20Libfm%20%28tarball%20release%29/PCManFM/pcmanfm-1.3.2.tar.xz
Summary  : a file manager replacement for Nautilus, Konqueror and Thunar
Group    : Development/Tools
License  : GPL-2.0
Requires: pcmanfm-bin = %{version}-%{release}
Requires: pcmanfm-data = %{version}-%{release}
Requires: pcmanfm-license = %{version}-%{release}
Requires: pcmanfm-locales = %{version}-%{release}
Requires: pcmanfm-man = %{version}-%{release}
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libfm)
BuildRequires : pkgconfig(x11)

%description
Compile the program with configure option --sysconfdir=/etc

%package bin
Summary: bin components for the pcmanfm package.
Group: Binaries
Requires: pcmanfm-data = %{version}-%{release}
Requires: pcmanfm-license = %{version}-%{release}

%description bin
bin components for the pcmanfm package.


%package data
Summary: data components for the pcmanfm package.
Group: Data

%description data
data components for the pcmanfm package.


%package dev
Summary: dev components for the pcmanfm package.
Group: Development
Requires: pcmanfm-bin = %{version}-%{release}
Requires: pcmanfm-data = %{version}-%{release}
Provides: pcmanfm-devel = %{version}-%{release}
Requires: pcmanfm = %{version}-%{release}

%description dev
dev components for the pcmanfm package.


%package license
Summary: license components for the pcmanfm package.
Group: Default

%description license
license components for the pcmanfm package.


%package locales
Summary: locales components for the pcmanfm package.
Group: Default

%description locales
locales components for the pcmanfm package.


%package man
Summary: man components for the pcmanfm package.
Group: Default

%description man
man components for the pcmanfm package.


%prep
%setup -q -n pcmanfm-1.3.2
cd %{_builddir}/pcmanfm-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612811300
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1612811300
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pcmanfm
cp %{_builddir}/pcmanfm-1.3.2/COPYING %{buildroot}/usr/share/package-licenses/pcmanfm/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
%make_install
%find_lang pcmanfm

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pcmanfm

%files data
%defattr(-,root,root,-)
/usr/share/applications/pcmanfm-desktop-pref.desktop
/usr/share/applications/pcmanfm.desktop
/usr/share/pcmanfm/ui/about.ui
/usr/share/pcmanfm/ui/autorun.ui
/usr/share/pcmanfm/ui/connect.ui
/usr/share/pcmanfm/ui/desktop-pref.ui
/usr/share/pcmanfm/ui/pref.ui

%files dev
%defattr(-,root,root,-)
/usr/include/pcmanfm-modules.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pcmanfm/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pcmanfm.1

%files locales -f pcmanfm.lang
%defattr(-,root,root,-)

